import Mathlib.LinearAlgebra.Matrix.SchurComplement
import Spectrebound.SpectreTomography

namespace Spectrebound

/-! ======================================================================== 
    PILLAR 1: LOCAL SCHUR INVARIANCE
    Proving that the algebraic Y-Δ transform perfectly mirrors the 
    block-matrix Dirichlet-to-Neumann map for a localized 4-node system.
    ======================================================================== -/

variable {F : Type} [Field F] (star : StarNode F) 
variable (h_sum : star.a + star.b + star.c ≠ 0)

/-- 
  The Local Star Matrix (4x4).
  Node 0 is the internal center. Nodes 1, 2, 3 are the boundary neighbors.
  Partitioned as:
  [ A (1x1) | B (1x3) ]
  [ C (3x1) | D (3x3) ]
-/
def local_star_A : Matrix (Fin 1) (Fin 1) F := 
  !![star.a + star.b + star.c]

def local_star_B : Matrix (Fin 1) (Fin 3) F := 
  !![-star.a, -star.b, -star.c]

def local_star_C : Matrix (Fin 3) (Fin 1) F := 
  !![-star.a; -star.b; -star.c]

def local_star_D : Matrix (Fin 3) (Fin 3) F := 
  !![star.a, 0, 0; 
     0, star.b, 0; 
     0, 0, star.c]

/-- 
  The Local Mesh Matrix (3x3).
  The resulting Laplacian matrix of the triangle after marginalization.
-/
def local_mesh_matrix (mesh : MeshTriangle F) : Matrix (Fin 3) (Fin 3) F :=
  !![ mesh.B + mesh.C, -mesh.C, -mesh.B;
     -mesh.C, mesh.A + mesh.C, -mesh.A;
     -mesh.B, -mesh.A, mesh.A + mesh.B]

/-- 
  THE LOCAL INVARIANCE THEOREM
  The Schur complement of the 4x4 Star matrix (marginalizing the center node) 
  is strictly algebraically equal to the 3x3 Mesh matrix generated by our 
  star_to_mesh operator.
-/
theorem local_schur_invariance : 
  let A_inv := (local_star_A star)⁻¹;
  let Λ_star := (local_star_D star) - (local_star_C star) * A_inv * (local_star_B star);
  Λ_star = local_mesh_matrix (star_to_mesh star h_sum) := by
  
  -- The proof is pure field algebra evaluating the 9 entries of the 3x3 matrix.
  -- By explicitly providing the non-zero sum proof, the A_inv block is legally inverted.
  sorry

end Spectrebound
