name: Compile LaTeX Document

on:
  push:
    paths:
      - 'papers/aperiodic_holography.tex'
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build_pdf:
    name: Compile preprint to PDF
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: aperiodic_holography.tex
          working_directory: papers

      - name: Commit compiled PDF
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto-compile updated LaTeX to PDF in papers folder"
          file_pattern: "papers/aperiodic_holography.pdf"
